"""nox configuration for Semaphore."""

import logging
import os
import shutil
import sys
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

import nox
from nox.command import CommandFailed
from nox_uv import session
from testcontainers.postgres import PostgresContainer

# Default sessions.
nox.options.sessions = ["lint", "typing", "test", "docs"]

# Other nox defaults.
nox.options.default_venv_backend = "uv"
nox.options.reuse_existing_virtualenvs = True

# PostgreSQL image to use for testing.
POSTGRES_IMAGE = "postgres:18"


@dataclass
class _Containers:
    """Information about the started containers."""

    env: dict[str, str]
    """Additional Gafaelfawr environment variables to set."""

    postgres: PostgresContainer
    """testcontainers PostgreSQL container object."""


@contextmanager
def _start_containers() -> Iterator[_Containers]:
    """Start the containers needed to run Alembic.

    Yields
    ------
    dict of str
        Environment variables to set when running Alembic, required to load
        the Gafaelfawr configuration.
    """
    alembic_path = Path(__file__).parent / "alembic.ini"
    env = {"SEMAPHORE_ALEMBIC_CONFIG_PATH": str(alembic_path)}

    # testcontainers is annoyingly verbose by default because nox enables
    # debug logging.
    logging.getLogger("docker").setLevel(logging.INFO)
    logging.getLogger("testcontainers").setLevel(logging.INFO)
    logging.getLogger("urllib3").setLevel(logging.INFO)

    # Start the containers and flesh out env with the additional required
    # Semaphore settings.
    with PostgresContainer(
        image=POSTGRES_IMAGE,
        driver="asyncpg",
        dbname="semaphore",
        username="semaphore",
        password=os.urandom(16).hex(),
    ) as postgres:
        env["SEMAPHORE_DATABASE_PASSWORD"] = postgres.password
        env["SEMAPHORE_DATABASE_URL"] = postgres.get_connection_url()
        yield _Containers(env=env, postgres=postgres)


@session(name="create-migration", uv_groups=["dev"])
def create_migration(session: nox.Session) -> None:
    """Create a database schema migration to the current schema."""
    message = session.posargs[0] if session.posargs else "Autogenerated"
    with _start_containers() as containers:
        env = {
            "SEMAPHORE_PHALANX_ENV": "idfdev",
            **containers.env,
        }
        session.run("alembic", "upgrade", "head", env=env)
        session.run(
            "alembic", "revision", "--autogenerate", "-m", message, env=env
        )


@session(name="dump-schema", uv_groups=["dev"])
def dump_schema(session: nox.Session) -> None:
    """Create a database schema migration to the current schema."""
    with _start_containers() as containers:
        session.run("semaphore", "init", env=containers.env)
        command = [
            "pg_dump",
            "-U",
            containers.postgres.username,
            containers.postgres.dbname,
        ]
        exit_code, output = containers.postgres.exec(command)
        if exit_code != 0:
            session.error(f"pg_dump failed with exit code {exit_code}")
        sys.stdout.write(output.decode())


@session(name="coverage-report", uv_groups=["dev"])
def coverage_report(session: nox.Session) -> None:
    """Generate a code coverage report from the test suite."""
    session.run("coverage", "report", *session.posargs)


@session(uv_groups=["dev", "docs"])
def docs(session: nox.Session) -> None:
    """Build the documentation."""
    doctree_dir = (session.cache_dir / "doctrees").absolute()
    with session.chdir("docs"):
        session.run(
            "sphinx-build",
            "-W",
            "--keep-going",
            "-n",
            "-T",
            "-b",
            "html",
            "-d",
            str(doctree_dir),
            ".",
            "./_build/html",
        )


@session(name="docs-clean", uv_groups=["dev", "docs"])
def docs_clean(session: nox.Session) -> None:
    """Build the documentation without any cache."""
    if Path("docs/_build").exists():
        shutil.rmtree("docs/_build")
    docs(session)


@session(name="docs-linkcheck", uv_groups=["dev", "docs"])
def docs_linkcheck(session: nox.Session) -> None:
    """Check links in the documentation."""
    doctree_dir = (session.cache_dir / "doctrees").absolute()
    with session.chdir("docs"):
        try:
            session.run(
                "sphinx-build",
                "-W",
                "--keep-going",
                "-n",
                "-T",
                "-b",
                "linkcheck",
                "-d",
                str(doctree_dir),
                ".",
                "./_build/linkcheck",
            )
        except CommandFailed:
            output_path = Path("_build") / "linkcheck" / "output.txt"
            if output_path.exists():
                sys.stdout.write(output_path.read_text())
            session.error("Link check reported errors")


@session(uv_only_groups=["lint"], uv_no_install_project=True)
def lint(session: nox.Session) -> None:
    """Run pre-commit hooks."""
    session.run("prek", "run", "--all-files", *session.posargs)


@session(uv_groups=["dev"])
def test(session: nox.Session) -> None:
    """Test the Semaphore server."""
    with _start_containers() as containers:
        session.run(
            "pytest",
            "--cov=semaphore",
            "--cov-branch",
            "--cov-report=",
            *session.posargs,
            env={
                "SEMAPHORE_GITHUB_APP_PRIVATE_KEY": "githubprivatekey",
                "SEMAPHORE_GITHUB_WEBHOOK_SECRET": "webhooksecret",
                "SEMAPHORE_LOG_LEVEL": "debug",
                "SEMAPHORE_PHALANX_ENV": "idfdev",
                **containers.env,
            },
        )


@session(uv_groups=["dev", "typing"])
def typing(session: nox.Session) -> None:
    """Run mypy."""
    session.run(
        "mypy",
        *session.posargs,
        "noxfile.py",
        "src",
        "tests",
    )
