"""Initial schema

Revision ID: fefe038bfd91
Revises:
Create Date: 2026-06-16 21:40:24.561752+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fefe038bfd91"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipient", sa.String(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("read", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "by_created", "user_notification", ["created", "id"], unique=False
    )
    op.create_index(
        "by_recipient",
        "user_notification",
        ["recipient", "created", "id"],
        unique=False,
    )
    op.create_index(
        "by_sender",
        "user_notification",
        ["sender", "created", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("by_sender", table_name="user_notification")
    op.drop_index("by_recipient", table_name="user_notification")
    op.drop_index("by_created", table_name="user_notification")
    op.drop_table("user_notification")
    # ### end Alembic commands ###
