"""Add index for marking notifications read

Revision ID: 7d4017e3ba52
Revises: 0942b43bc681
Create Date: 2026-06-17 23:23:07.046705+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d4017e3ba52"
down_revision: str | Sequence[str] | None = "0942b43bc681"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "by_recipient_id",
        "user_notification",
        ["recipient", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("by_recipient_id", table_name="user_notification")
    # ### end Alembic commands ###
