"""Allow null notification body

Revision ID: 0942b43bc681
Revises: fefe038bfd91
Create Date: 2026-06-17 16:19:48.852411+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0942b43bc681"
down_revision: str | Sequence[str] | None = "fefe038bfd91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_notification", "body", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_notification", "body", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
